name: Zgłoszenie Błędu
description: Zgłoś błąd dokumentując co nie działa i jak powinno działać.
type: bug
projects: ["fundacjawspinka/1"]
priorytet: niski
body:
  - type: textarea
    id: repro
    attributes:
      label: Kroki reprodukcji
      description: Co trzeba zrobić krok po kroku?
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Oczekiwane zachowanie
      description: Jak powinno to wyglądać, zachowywać się?
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Rzeczywiste zachowanie
      description: Jak obecnie to wygląda, zachowuje się?
    validations:
      required: true
