name: "Zadanie Techniczne"
description: "Zgłoś zadanie developerskie | infra | CI/CD"
type: zadanie
projects: ["fundacjawspinka/1"]
body:
  - type: textarea
    id: task_description
    attributes:
      label: "Opis zadania"
      description: "Uzupełnij tyle, ile możesz. Im konkretniej, tym łatwiej estymować i dowieźć."
      placeholder: "W tym zadaniu należy ..."
    validations:
      required: true

  - type: textarea
    id: definition_of_done
    attributes:
      label: "Definition of Done"
      description: "Warunki ukończenia (checklista)."
      placeholder: |
        - [ ] Kod + review
        - [ ] Testy (unit/e2e) zaktualizowane
        - [ ] Dokumentacja
        - [ ] Deploy zweryfikowany
    validations:
      required: true
