name: "Test Case"
description: "Przypadek testowy – biblioteka testów manualnych"
type: testcase
projects: ["fundacjawspinka/1"]
body:
  - type: dropdown
    id: area
    attributes:
      label: Obszar
      description: Obszar aplikacji mobilnej, panelu admina
      options:
        - Obiekty wspinaczkowe
        - Wyszukiwarka
        - Mapa
        - Auth
        - Profil
        - Settings
        - Organizer
        - Profil wspinacza
        - Użytkownicy
        - Media
    validations:
      required: true

  - type: textarea
    id: preconditions
    attributes:
      label: Konfiguracja wstępna
      description: "Stan aplikacji, konta, feature flagi, uprawnienia, środowisko, dane testowe (bez sekretów)"
      placeholder: |
        - User: wylogowany
        - Env: QA
        - Dane: konto testowe X
    validations:
      required: false

  - type: textarea
    id: steps_expected
    attributes:
      label: Kroki
      description: "Minimalnie: kroki i oczekiwane. Jeśli masz warianty (Google/Apple/Facebook), opisz je w sekcji Warianty"
    validations:
      required: true

  - type: textarea
    id: variants
    attributes:
      label: Warianty / Parametry (opcjonalnie)
      description: "Parametryzacja testu (np. provider=Google/Apple/Facebook, scenariusze cancel, brak sieci, różne role)"
    validations:
      required: false
